
package icons;
import java.sql.*;
import Studentdashboard.ConnectionProvider;
import Studentdashboard.ConnectionProvider;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

//import Project.ConnectionProvider;
  



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class IssuedBooks extends javax.swing.JFrame {

    /**
     * 
     */
    public IssuedBooks() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mybookstable = new rojeru_san.complementos.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Issued Books");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        mybookstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Student ID", "Name", "Issue Date", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mybookstable.setColorBackgoundHead(new java.awt.Color(0, 0, 0));
        mybookstable.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        mybookstable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mybookstable.setRowHeight(40);
        mybookstable.setRowMargin(3);
        mybookstable.getTableHeader().setReorderingAllowed(false);
        mybookstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mybookstableMouseClicked(evt);
            }
        });
        mybookstable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                mybookstableComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(mybookstable);
        if (mybookstable.getColumnModel().getColumnCount() > 0) {
            mybookstable.getColumnModel().getColumn(0).setResizable(false);
            mybookstable.getColumnModel().getColumn(1).setResizable(false);
            mybookstable.getColumnModel().getColumn(2).setResizable(false);
            mybookstable.getColumnModel().getColumn(3).setResizable(false);
            mybookstable.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 640, 370));

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Studentdashboard/bgm.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        setSize(new java.awt.Dimension(791, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
 ResultSet rsl = null;
    try {
        con = ConnectionProvider.getCon();
        st = con.createStatement();
        String query = "SELECT issue.StudentID, issue.BookID, books.Name, issue.IssueDate, issue.Duedate " +
                       "FROM students " +
                       "INNER JOIN issue ON students.id = issue.StudentID " +
                       "INNER JOIN books ON books.BookID = issue.BookID " +
                       "WHERE issue.Returned = 'NO'";
       rs = st.executeQuery(query);           
       mybookstable.setModel(DbUtils.resultSetToTableModel(rs));
      
    rsl = st.executeQuery(query);           
    mybookstable.setModel(DbUtils.resultSetToTableModel(rsl));
   
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
}
   finally {
        try {
            if (rs != null) rs.close();
            if (st != null) st.close();
            if (con != null) con.close();
                        if (rsl != null) rsl.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    

    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mybookstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybookstableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mybookstableMouseClicked

    private void mybookstableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mybookstableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_mybookstableComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuedBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSTableMetro mybookstable;
    // End of variables declaration//GEN-END:variables
}
