/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Studentdashboard;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import java.time.ZoneId;
import Studentdashboard.ConnectionProvider;
import java.util.Date;
/**
 *
 * @author dell
 */
public class Borrow_books extends javax.swing.JFrame {
private String studentId;
    /**
     * Creates new form Borrow_books
     */
    public Borrow_books(String studentId) {
        initComponents();
               this.studentId = studentId;  // Correctly assign the passed student ID
        txt_studentid.setText(studentId);  // Display the student ID in the text field
        txt_studentid.setEditable(false);
    }
     
     private void searchBookAndSetDetails(String bookId, String studentId) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Connect to the database
            conn = ConnectionProvider.getCon();

            // Check if the book is already allotted to the student
            String checkQuery = "SELECT * FROM  issue WHERE BookID = ? AND StudentID = ? AND Returned='NO'";
            pstmt = conn.prepareStatement(checkQuery);
            pstmt.setString(1, bookId);
            pstmt.setString(2, studentId);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "The book is already allotted to this student.");
                return;
            }

            // Fetch book details if it's not already allotted
            String bookQuery = "SELECT Name FROM books WHERE BookID = ?";
            pstmt = conn.prepareStatement(bookQuery);
            pstmt.setString(1, bookId);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                String bookName = rs.getString("Name");
                txt_bookname.setText(bookName);

                // Set today's date as the issue date
                LocalDate today = LocalDate.now();
                Date issueDate = Date.from(today.atStartOfDay(ZoneId.systemDefault()).toInstant());
                txtissuedate.setDatoFecha(issueDate);

                // Set the due date to one month from today
                LocalDate dueDate = today.plusMonths(1);
                Date dueDateValue = Date.from(dueDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
                txtduedate.setDatoFecha(dueDateValue);
            } else {
                JOptionPane.showMessageDialog(null, "Book not found.");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            // Close resources
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtissuedate = new rojeru_san.componentes.RSDateChooser();
        txtduedate = new rojeru_san.componentes.RSDateChooser();
        txt_bookname = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        Issuebtn = new javax.swing.JButton();
        txt_studentid = new app.bolivia.swing.JCTextField();
        closebtn = new javax.swing.JButton();
        txt_bookid = new app.bolivia.swing.JCTextField();
        searchbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 255));
        jLabel30.setText("Due Date :");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 255));
        jLabel29.setText("Issue Date :");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        txtissuedate.setPlaceholder("Enter Issue Date");
        getContentPane().add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        txtduedate.setPlaceholder("Enter Due Date");
        getContentPane().add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        txt_bookname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_bookname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_bookname.setPlaceholder("Enter Book ID");
        getContentPane().add(txt_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Book Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 180, 40));

        Issuebtn.setBackground(new java.awt.Color(102, 255, 102));
        Issuebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Issuebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Studentdashboard/return book png.png"))); // NOI18N
        Issuebtn.setText("Borrow");
        Issuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Issuebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 140, 40));

        txt_studentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_studentid.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_studentid.setPlaceholder("Enter Student ID");
        getContentPane().add(txt_studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        closebtn.setBackground(new java.awt.Color(255, 102, 102));
        closebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Studentdashboard/red-x-mark-transparent-background-3.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 130, 40));

        txt_bookid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_bookid.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_bookid.setPlaceholder("Enter Book ID");
        getContentPane().add(txt_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        searchbtn.setBackground(new java.awt.Color(0, 0, 0));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Studentdashboard/search.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 160, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Book ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 120, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Student ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 170, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Studentdashboard/bgm.jpg"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(500, 830));
        jLabel6.setMinimumSize(new java.awt.Dimension(500, 830));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Library_Book_532388_1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1290, 700));

        setSize(new java.awt.Dimension(1028, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IssuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuebtnActionPerformed
   String bookID = txt_bookid.getText();
    String studentID = txt_studentid.getText();
    Date issueDate = txtissuedate.getDatoFecha();
    Date dueDate = txtduedate.getDatoFecha();
    
    if (bookID.isEmpty() || studentID.isEmpty() || issueDate == null || dueDate == null) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields before issuing.");
        return;
    }

    Connection conn = null;
    PreparedStatement checkStmt = null;
    PreparedStatement issueStmt = null;
    ResultSet rs = null;

    try {
        // Connect to the database
        conn = ConnectionProvider.getCon();

        // Check if the book is already issued
        String checkQuery = "SELECT * FROM issue WHERE BookID = ? AND StudentID = ? AND Returned='NO'";
        checkStmt = conn.prepareStatement(checkQuery);
        checkStmt.setString(1, bookID);
        checkStmt.setString(2, studentID);
        rs = checkStmt.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "This book is already issued to this student.");
            return;
        }

       
        String insertQuery = "INSERT INTO issue (BookID, StudentID, IssueDate, DueDate,Returned) VALUES (?, ?, ?, ?, ?)";
        issueStmt = conn.prepareStatement(insertQuery);
        issueStmt.setString(1, bookID);
        issueStmt.setString(2, studentID);
        issueStmt.setDate(3, new java.sql.Date(issueDate.getTime()));
        issueStmt.setDate(4, new java.sql.Date(dueDate.getTime()));
        issueStmt.setString(5, "NO");
        int rowsInserted = issueStmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Book issued successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to issue the book. Please try again.");
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (checkStmt != null) checkStmt.close();
            if (issueStmt != null) issueStmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_IssuebtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
      String bookID = txt_bookid.getText();
        String studentID = txt_studentid.getText();
        
        if (bookID.isEmpty() || studentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter both Book ID and Student ID.");
        } else {
            searchBookAndSetDetails(bookID, studentId);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrow_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrow_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrow_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrow_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrow_books("36").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Issuebtn;
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton searchbtn;
    private app.bolivia.swing.JCTextField txt_bookid;
    private app.bolivia.swing.JCTextField txt_bookname;
    private app.bolivia.swing.JCTextField txt_studentid;
    private rojeru_san.componentes.RSDateChooser txtduedate;
    private rojeru_san.componentes.RSDateChooser txtissuedate;
    // End of variables declaration//GEN-END:variables
}
