/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminDashboard;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jframe.DBconnection;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author dell
 */
public class AllBooks extends javax.swing.JFrame {

    /**
     * Creates new form AllBooks
     */
    public AllBooks() {
        initComponents();
        displayBooksWithRSMetroTable();
    }


private void displayBooksWithRSMetroTable() {
     DefaultTableModel model = new DefaultTableModel(new Object[]{"Book ID", "Name", "Publisher", "Year","Price","Quantity"}, 0);
availablebooks.setModel(model);

    try {
        Connection con = DBconnection.getConnection();
        String sql = "SELECT * FROM books WHERE Quantity >= 0 ORDER BY Quantity ASC";
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            String bookId = rs.getString("BookID");
            String name = rs.getString("Name");
            String author = rs.getString("Publisher");
            String year = rs.getString("Year");
            String price = rs.getString("Price");
            int quantity = rs.getInt("Quantity");

            model.addRow(new Object[]{bookId, name, author,year,price, quantity});
        }

        rs.close();
        stmt.close();
        con.close();
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error fetching book data: " + e.getMessage());
    }

    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        availablebooks = new rojeru_san.complementos.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        availablebooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Name", "Publisher", "Year", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        availablebooks.setColorBackgoundHead(new java.awt.Color(0, 0, 0));
        availablebooks.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        availablebooks.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        availablebooks.setRowHeight(40);
        availablebooks.setRowMargin(3);
        availablebooks.getTableHeader().setReorderingAllowed(false);
        availablebooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availablebooksMouseClicked(evt);
            }
        });
        availablebooks.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                availablebooksComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(availablebooks);
        if (availablebooks.getColumnModel().getColumnCount() > 0) {
            availablebooks.getColumnModel().getColumn(0).setResizable(false);
            availablebooks.getColumnModel().getColumn(1).setResizable(false);
            availablebooks.getColumnModel().getColumn(2).setResizable(false);
            availablebooks.getColumnModel().getColumn(3).setResizable(false);
            availablebooks.getColumnModel().getColumn(4).setResizable(false);
            availablebooks.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 780, 250));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available Books");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        Close.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Close.setText("Close");
        Close.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 80, -1));

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Studentdashboard/bgm.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void availablebooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availablebooksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_availablebooksMouseClicked

    private void availablebooksComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_availablebooksComponentShown

        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

        try {
            con = DBconnection.getConnection();
            st = con.createStatement();

            String studentID = "33";
            String query = "SELECT issue.BookID, books.Name, issue.IssueDate, issue.Duedate " +
            "FROM issue " +
            "INNER JOIN books ON books.BookID = issue.BookID " +
            "WHERE issue.StudentID = '" + studentID + "' AND issue.Returned = 'NO'";

            rs = st.executeQuery(query);
            availablebooks.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (st != null) st.close();
                if (con != null) con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_availablebooksComponentShown

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private rojeru_san.complementos.RSTableMetro availablebooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
